-- Oficinas associadas (rede de lojas) e serviços oferecidos.
-- Permite que um admin gerencie oficinas e serviços no futuro.

-- Tabela de oficinas/lojas
CREATE TABLE IF NOT EXISTS public.oficinas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  endereco text NOT NULL,
  cidade text NOT NULL,
  estado char(2) NOT NULL,
  cep text,
  horario_seg_sex text,
  horario_sabado text,
  tipo text NOT NULL DEFAULT 'loja' CHECK (tipo IN ('loja', 'truck_center', 'pit_stop')),
  telefone text,
  whatsapp text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (nome, cidade, estado)
);

-- Tabela de serviços (catálogo)
CREATE TABLE IF NOT EXISTS public.servicos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  categoria text NOT NULL CHECK (categoria IN ('leves_todos', 'leves_mecanica', 'pesada', 'pesada_mecanica')),
  UNIQUE (nome, categoria),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Relação N:N: quais serviços cada oficina oferece
CREATE TABLE IF NOT EXISTS public.oficina_servicos (
  oficina_id bigint NOT NULL REFERENCES public.oficinas(id) ON DELETE CASCADE,
  servico_id bigint NOT NULL REFERENCES public.servicos(id) ON DELETE CASCADE,
  PRIMARY KEY (oficina_id, servico_id)
);

CREATE INDEX IF NOT EXISTS idx_oficinas_estado ON public.oficinas(estado);
CREATE INDEX IF NOT EXISTS idx_oficinas_cidade ON public.oficinas(cidade);
CREATE INDEX IF NOT EXISTS idx_oficinas_tipo ON public.oficinas(tipo);
CREATE INDEX IF NOT EXISTS idx_oficinas_ativo ON public.oficinas(ativo);
CREATE INDEX IF NOT EXISTS idx_servicos_categoria ON public.servicos(categoria);
CREATE INDEX IF NOT EXISTS idx_oficina_servicos_oficina ON public.oficina_servicos(oficina_id);
CREATE INDEX IF NOT EXISTS idx_oficina_servicos_servico ON public.oficina_servicos(servico_id);

COMMENT ON TABLE public.oficinas IS 'Oficinas/lojas da rede associada (ex: Japurá Pneus)';
COMMENT ON TABLE public.servicos IS 'Catálogo de serviços (alinhamento, balanceamento, mecânica, etc.)';
COMMENT ON TABLE public.oficina_servicos IS 'Serviços disponíveis em cada oficina';
