-- Tabelas abastecimentos e manutencoes (se não existirem)
-- Garante vehicle_id e datas como DATE
-- Executar no Supabase SQL Editor se as tabelas ainda não existirem

-- Abastecimentos
CREATE TABLE IF NOT EXISTS public.abastecimentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id bigint NOT NULL REFERENCES public.veiculo(id) ON DELETE CASCADE,
  data date NOT NULL,
  litros numeric(10,2),
  valor_total numeric(10,2),
  km integer,
  posto text,
  tipo text,
  observacoes text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_abastecimentos_vehicle_id ON public.abastecimentos(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_abastecimentos_data ON public.abastecimentos(data);

-- Manutencoes
CREATE TABLE IF NOT EXISTS public.manutencoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id bigint NOT NULL REFERENCES public.veiculo(id) ON DELETE CASCADE,
  data date NOT NULL,
  tipo text NOT NULL,
  valor numeric(10,2) NOT NULL,
  km integer,
  oficina text,
  notas text,
  foto_nf_url text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_manutencoes_vehicle_id ON public.manutencoes(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_manutencoes_data ON public.manutencoes(data);

-- RLS: permitir leitura/escrita anônima para desenvolvimento (ajustar em produção)
ALTER TABLE public.veiculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.abastecimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manutencoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all veiculo" ON public.veiculo;
CREATE POLICY "Allow all veiculo" ON public.veiculo FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all abastecimentos" ON public.abastecimentos;
CREATE POLICY "Allow all abastecimentos" ON public.abastecimentos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all manutencoes" ON public.manutencoes;
CREATE POLICY "Allow all manutencoes" ON public.manutencoes FOR ALL USING (true) WITH CHECK (true);
